<?php
    session_start();
    if (!$_SESSION["log"]){
    	header("Location:index.php");
    }
    include 'db.php';


    $db = $_SESSION["db"];
    $module = $_GET['module'];
    $id = $_GET['id'];


    connectDB($db);

    switch ($module) {
        case 'GAS':
            $qry1="SELECT
                    Gasto.ID,
                    Gasto.Empresa,
                    Gasto.Mov,
                    Gasto.MovID,
                    Gasto.FechaEmision,
                    Gasto.UltimoCambio,
                    Gasto.Acreedor,
                    Gasto.Moneda,
                    Gasto.TipoCambio,
                    Gasto.Proyecto,
                    Gasto.Usuario,
                    Gasto.Autorizacion,
                    Gasto.DocFuente,
                    Gasto.Observaciones,
                    Gasto.Clase,
                    Gasto.SubClase,
                    Gasto.Estatus,
                    Gasto.Situacion,
                    Gasto.SituacionFecha,
                    Gasto.SituacionUsuario,
                    Gasto.SituacionNota,
                    Gasto.Periodicidad,
                    Gasto.TieneRetencion,
                    Gasto.Condicion,
                    Gasto.Vencimiento,
                    Gasto.CtaDinero,
                    Gasto.FormaPago,
                    Gasto.Importe,
                    Gasto.Retencion,
                    Gasto.Impuestos,
                    Gasto.Saldo,
                    Gasto.Anticipo,
                    Gasto.MovAplica,
                    Gasto.MovAplicaID,
                    Gasto.Multiple,
                    Gasto.OrigenTipo,
                    Gasto.Origen,
                    Gasto.OrigenID,
                    Gasto.Poliza,
                    Gasto.PolizaID,
                    Gasto.GenerarPoliza,
                    Gasto.ContID,
                    Gasto.Ejercicio,
                    Gasto.Periodo,
                    Gasto.FechaRegistro,
                    Gasto.FechaConclusion,
                    Gasto.FechaCancelacion,
                    Gasto.FechaRequerida,
                    Gasto.GenerarDinero,
                    Gasto.Dinero,
                    Gasto.DineroID,
                    Gasto.DineroCtaDinero,
                    Gasto.CXP,
                    Gasto.AnexoModulo,
                    Gasto.AnexoID,
                    Gasto.ProdSerieLote,
                    Gasto.Sucursal,
                    Gasto.SucursalDestino,
                    Gasto.SucursalOrigen,
                    Gasto.Mensaje,
                    Gasto.Actividad,
                    Gasto.IVAFiscal,
                    Gasto.IEPSFiscal,
                    Gasto.EspacioResultado,
                    Gasto.UEN,
                    Gasto.EstaImpreso,
                    Gasto.AF,
                    Gasto.AFArticulo,
                    Gasto.AFSerie,
                    Gasto.Comentarios,
                    Gasto.ConVigencia,
                    Gasto.VigenciaDesde,
                    Gasto.VigenciaHasta,
                    Gasto.ContratoTipo,
                    Gasto.ContratoDescripcion,
                    Gasto.ContratoSerie,
                    Gasto.ContratoValor,
                    Gasto.ContratoValorMoneda,
                    Gasto.ContratoSeguro,
                    Gasto.ContratoResponsable,
                    Gasto.ContratoVencimiento,
                    Gasto.Prioridad,
                    Gasto.Nota,
                    Gasto.SubModulo,
                    Gasto.ClienteRef,
                    Gasto.ArticuloRef,
                    Gasto.ContUso,
                    Gasto.ContUso2,
                    Gasto.ContUso3,
                    Gasto.ContratoID,
                    Gasto.ContratoMov,
                    Gasto.ContratoMovID,
                    Gasto.TipoComprobante,
                    Gasto.SustentoComprobante,
                    Gasto.TipoIdentificacion,
                    Gasto.DerechoDevolucion,
                    Gasto.Establecimiento,
                    Gasto.PuntoEmision,
                    Gasto.SecuencialSRI,
                    Gasto.AutorizacionSRI,
                    Gasto.VigenteA,
                    Gasto.SecuenciaRetencion,
                    Gasto.Comprobante,
                    Gasto.FechaContableMov,
                    Gasto.PuntoEmisionRetencion,
                    Gasto.SecuencialSRIRetencion,
                    Mon.Moneda,
                    Mon.TipoCambio,
                    Mon.TipoCambioVenta,
                    Mon.TipoCambioCompra,
                    MovTipo.SubClave,
                    MovTipo.DiasVencimiento,
                    MovTipo.EditarDeptoDetallista,
                    MovTipo.ReservarCP,
                    MovTipo.EcuadorMostrarAnexo,
                    Prov.Proveedor,
                    Prov.Nombre,
                    Prov.Tipo,
                    Prov.ZonaImpuesto,
                    Prov.Proyecto,
                    -- Prov.Condicion,
                    Prov.CtaDinero,
                    Prov.Estatus,
                    Prov.DefMoneda,
                    Prov.Mensaje,
                    -- Prov.FormaPago,
                    CtaDinero.CtaDinero,
                    CtaDinero.Descripcion,
                    CtaDinero.Tipo,
                    CtaDinero.Estatus,
                    CtaDinero.Mensaje,
                    MensajeLista.Mensaje,
                    MensajeLista.Descripcion,
                    MensajeLista.Tipo,
                    UEN.UEN,
                    -- UEN.Nombre,
                    Art.Articulo,
                    Art.Descripcion1,
                    ActivoF.Serie,
                    ProyectoDEnFirme.Asunto,
                    CentroCostos.CentroCostos,
                    CentroCostos2.CentroCostos2,
                    CentroCostos3.CentroCostos3,
                    TipoComprobante.Concepto,
                    TipoRegistro.Concepto,
                    SustentoComprobante.Concepto
                    FROM Gasto
                    LEFT OUTER JOIN MovTipo ON 'GAS'=MovTipo.Modulo AND Gasto.Mov=MovTipo.Mov
                    JOIN Mon ON Gasto.Moneda=Mon.Moneda
                    JOIN Prov ON Gasto.Acreedor=Prov.Proveedor
                    LEFT OUTER JOIN CtaDinero ON Gasto.CtaDinero=CtaDinero.CtaDinero
                    LEFT OUTER JOIN MensajeLista ON Gasto.Mensaje=MensajeLista.Mensaje
                    LEFT OUTER JOIN UEN ON Gasto.UEN=UEN.UEN
                    LEFT OUTER JOIN Art ON Gasto.AFArticulo=Art.Articulo
                    LEFT OUTER JOIN ActivoF ON Gasto.Empresa=ActivoF.Empresa AND Gasto.AFArticulo=ActivoF.Articulo AND Gasto.AFSerie=ActivoF.Serie
                    LEFT OUTER JOIN ProyectoDEnFirme ON Gasto.Proyecto=ProyectoDEnFirme.Proyecto AND Gasto.Actividad=ProyectoDEnFirme.Actividad
                    LEFT OUTER JOIN CentroCostos ON Gasto.ContUso=CentroCostos.CentroCostos
                    LEFT OUTER JOIN CentroCostos2 ON Gasto.ContUso2=CentroCostos2.CentroCostos2
                    LEFT OUTER JOIN CentroCostos3 ON Gasto.ContUso3=CentroCostos3.CentroCostos3
                    LEFT OUTER JOIN TipoComprobante ON Gasto.TipoComprobante=TipoComprobante.TipoComprobante
                    LEFT OUTER JOIN SustentoComprobante ON Gasto.SustentoComprobante=SustentoComprobante.SustentoComprobante
                    LEFT OUTER JOIN TipoRegistro ON Gasto.TipoIdentificacion=TipoRegistro.TipoRegistro
                     WHERE Gasto.ID =".$id;

            $qry2="SELECT GastoD.ID,
                    GastoD.Renglon,
                    GastoD.RenglonSub,
                    GastoD.Fecha,
                    GastoD.Concepto,
                    GastoD.Referencia,
                    GastoD.Cantidad,
                    GastoD.ImporteConImpuesto,
                    GastoD.Precio,
                    GastoD.Importe,
                    GastoD.Impuestos,
                    GastoD.Impuestos2,
                    GastoD.Impuestos3,
                    GastoD.Retencion as RetencionG,
                    GastoD.Retencion2 as RetencionG2,
                    GastoD.Retencion3,
                    GastoD.ContUso,
                    GastoD.Sucursal,
                    GastoD.SucursalOrigen,
                    GastoD.Proyecto,
                    GastoD.Actividad,
                    GastoD.DescripcionExtra,
                    GastoD.VIN,
                    GastoD.Espacio,
                    GastoD.UEN,
                    GastoD.AcreedorRef,
                    GastoD.AFArticulo,
                    GastoD.AFSerie,
                    GastoD.PorcentajeDeducible,
                    GastoD.Lectura,
                    GastoD.LecturaAnterior,
                    GastoD.EndosarA,
                    GastoD.Provision,
                    GastoD.Personal,
                    GastoD.DepartamentoDetallista,
                    GastoD.PresupuestoEsp,
                    GastoD.Recurso,
                    GastoD.ContUso2,
                    GastoD.ContUso3,
                    GastoD.ABC,
                    GastoD.ClavePresupuestal,
                    GastoD.TipoImpuesto1,
                    GastoD.TipoImpuesto2,
                    GastoD.TipoImpuesto3,
                    GastoD.TipoImpuesto4,
                    GastoD.TipoRetencion1,
                    GastoD.TipoRetencion2,
                    GastoD.TipoRetencion3,
                    GastoD.Impuesto1,
                    GastoD.Impuesto2,
                    GastoD.Impuesto3,
                    GastoD.TipoComprobante,
                    GastoD.SustentoComprobante,
                    GastoD.TipoIdentificacion,
                    GastoD.DerechoDevolucion,
                    GastoD.Establecimiento,
                    GastoD.PuntoEmision,
                    GastoD.SecuencialSRI,
                    GastoD.AutorizacionSRI,
                    GastoD.VigenteA,
                    GastoD.SecuenciaRetencion,
                    GastoD.Comprobante,
                    GastoD.FechaContableMov,
                    GastoD.EcuadorTipoOperacionGasto,
                    GastoD.Impuesto5,
                    GastoD.Impuestos5,
                    GastoD.TipoImpuesto5,
                    GastoD.CambioImpuesto,
                    Concepto.Modulo,
                    -- Concepto.Concepto,
                    Concepto.EsDeducible,
                    -- Concepto.PorcentajeDeducible,
                    Concepto.LimiteDeducible,
                    Concepto.Impuestos as PorcentajeImpuestos,
                    -- Concepto.Retencion,
                    Concepto.Retencion2,
                    Concepto.Retencion3,
                    Concepto.Proyecto,
                    Concepto.EsInventariable,
                    Concepto.Articulo,
                    -- Concepto.ContUso,
                    Concepto.ContUso2,
                    Concepto.ContUso3,
                    Concepto.ObjetoGasto,
                    CentroCostos.CentroCostos,
                    Espacio.Espacio,
                    Espacio.Nombre,
                    Espacio.NumeroEconomico,
                    UEN.UEN,
                    UEN.Nombre,
                    Acreedor.Proveedor,
                    Acreedor.Nombre,
                    Acreedor2.Nombre,
                    Art.Articulo,
                    Art.Descripcion1,
                    ActivoF.Serie,
                    -- ActivoF.PorcentajeDeducible,
                    VIN.VIN,
                    Personal.Personal,
                    Personal.ApellidoPaterno,
                    Personal.ApellidoMaterno,
                    Personal.Nombre,
                    DepartamentoDetallista.Nombre,
                    ProyectoDEnFirme.Asunto,
                    Recurso.Nombre,
                    CentroCostos2.CentroCostos2,
                    CentroCostos3.CentroCostos3,
                    ClavePresupuestal.Nombre,
                    ClavePresupuestal.ObjetoGasto,
                    -- TipoComprobante.Concepto,
                    -- TipoRegistro.Concepto,
                    -- SustentoComprobante.Concepto,
                    (SELECT CantidadReservada FROM InvD WHERE ID = GastoD.InvID AND Renglon = GastoD.Renglon AND RenglonSub = GastoD.RenglonSub) CantidadReservada,
                    (SELECT CantidadOrdenada FROM InvD WHERE ID = GastoD.InvID AND Renglon = GastoD.Renglon AND RenglonSub = GastoD.RenglonSub) CantidadOrdenada,
                    (SELECT CantidadPendiente FROM InvD WHERE ID = GastoD.InvID AND Renglon = GastoD.Renglon AND RenglonSub = GastoD.RenglonSub) CantidadPendiente FROM GastoD
                    LEFT OUTER JOIN Concepto ON 'GAS'=Concepto.Modulo AND GastoD.Concepto=Concepto.Concepto
                    LEFT OUTER JOIN CentroCostos ON GastoD.ContUso=CentroCostos.CentroCostos
                    LEFT OUTER JOIN Espacio ON GastoD.Espacio=Espacio.Espacio
                    LEFT OUTER JOIN UEN ON GastoD.UEN=UEN.UEN
                    LEFT OUTER JOIN Prov Acreedor ON GastoD.AcreedorRef=Acreedor.Proveedor
                    LEFT OUTER JOIN Art ON GastoD.AFArticulo=Art.Articulo
                    LEFT OUTER JOIN ActivoF ON GastoD.AFArticulo=ActivoF.Articulo AND GastoD.AFSerie=ActivoF.Serie AND 'ROCHE'=ActivoF.Empresa
                    LEFT OUTER JOIN Prov Acreedor2 ON GastoD.EndosarA=Acreedor2.Proveedor
                    LEFT OUTER JOIN VIN ON GastoD.VIN=VIN.VIN
                    LEFT OUTER JOIN Personal ON GastoD.Personal=Personal.Personal
                    LEFT OUTER JOIN DepartamentoDetallista ON GastoD.DepartamentoDetallista=DepartamentoDetallista.Departamento
                    LEFT OUTER JOIN ProyectoDEnFirme ON GastoD.Proyecto=ProyectoDEnFirme.Proyecto AND GastoD.Actividad=ProyectoDEnFirme.Actividad
                    LEFT OUTER JOIN Recurso ON GastoD.Recurso=Recurso.Recurso
                    LEFT OUTER JOIN CentroCostos2 ON GastoD.ContUso2=CentroCostos2.CentroCostos2
                    LEFT OUTER JOIN CentroCostos3 ON GastoD.ContUso3=CentroCostos3.CentroCostos3
                    LEFT OUTER JOIN ClavePresupuestal ON GastoD.ClavePresupuestal=ClavePresupuestal.ClavePresupuestal
                    LEFT OUTER JOIN TipoComprobante ON GastoD.TipoComprobante=TipoComprobante.TipoComprobante
                    LEFT OUTER JOIN SustentoComprobante ON GastoD.SustentoComprobante=SustentoComprobante.SustentoComprobante
                    LEFT OUTER JOIN TipoRegistro ON GastoD.TipoIdentificacion=TipoRegistro.TipoRegistro
                     WHERE GastoD.ID = ".$id." ORDER BY GastoD.Renglon, GastoD.RenglonSub ";
            break;
        case 'COMS':
            $qry1 = "SELECT
                          Compra.ID,
                          Compra.Empresa,
                          Compra.Mov,
                          Compra.MovID,
                          Compra.FechaEmision,
                          Compra.UltimoCambio,
                          Compra.Concepto,
                          Compra.Proyecto,
                          Compra.Moneda,
                          Compra.TipoCambio,
                          Compra.Usuario,
                          Compra.Autorizacion,
                          Compra.Referencia,
                          Compra.DocFuente,
                          Compra.Observaciones,
                          Compra.Estatus,
                          Compra.Situacion,
                          Compra.SituacionFecha,
                          Compra.SituacionUsuario,
                          Compra.SituacionNota,
                          Compra.Directo,
                          Compra.VerDestino,
                          Compra.Prioridad,
                          Compra.RenglonID,
                          Compra.Proveedor,
                          Compra.FormaEnvio,
                          Compra.FechaEntrega,
                          Compra.FechaRequerida,
                          Compra.Almacen,
                          Compra.Condicion,
                          Compra.Vencimiento,
                          Compra.Manejo,
                          Compra.Fletes,
                          Compra.Instruccion,
                          Compra.Agente,
                          Compra.Descuento,
                          Compra.DescuentoGlobal,
                          Compra.Importe,
                          Compra.Impuestos,
                          Compra.Saldo,
                          Compra.DescuentoLineal,
                          Compra.OrigenTipo,
                          Compra.Origen,
                          Compra.OrigenID,
                          Compra.Poliza,
                          Compra.PolizaID,
                          Compra.Peso,
                          Compra.Volumen,
                          Compra.Atencion,
                          Compra.Causa,
                          Compra.Sucursal,
                          Compra.SucursalDestino,
                          Compra.SucursalOrigen,
                          Compra.ZonaImpuesto,
                          Compra.Idioma,
                          Compra.ListaPreciosEsp,
                          Compra.UEN,
                          Compra.Mensaje,
                          Compra.FormaEntrega,
                          Compra.CancelarPendiente,
                          Compra.LineaCredito,
                          Compra.TipoAmortizacion,
                          Compra.TipoTasa,
                          Compra.Comisiones,
                          Compra.ComisionesIVA,
                          Compra.VIN,
                          Compra.SubModulo,
                          Compra.AutoCargos,
                          Compra.TieneTasaEsp,
                          Compra.TasaEsp,
                          Compra.Cliente,
                          Compra.Actividad,
                          Compra.ContUso,
                          Compra.ContUso2,
                          Compra.ContUso3,
                          Compra.ContratoID,
                          Compra.ContratoMov,
                          Compra.ContratoMovID,
                          Compra.TipoComprobante,
                          Compra.SustentoComprobante,
                          Compra.TipoIdentificacion,
                          Compra.DerechoDevolucion,
                          Compra.Establecimiento,
                          Compra.PuntoEmision,
                          Compra.SecuencialSRI,
                          Compra.AutorizacionSRI,
                          Compra.VigenteA,
                          Compra.SecuenciaRetencion,
                          Compra.Comprobante,
                          Compra.FechaContableMov,
                          Compra.FechaProveedor,
                          Compra.PuntoEmisionRetencion,
                          Compra.SecuencialSRIRetencion,
                          MovTipo.ReservarCP,
                          MovTipo.EcuadorMostrarAnexo,
                          Cte.Nombre,
                          Condicion.Condicion,
                          Mon.Moneda,
                          Mon.TipoCambio,
                          Mon.TipoCambioVenta,
                          Mon.TipoCambioCompra,
                          Prov.Proveedor,
                          Prov.Nombre,
                          Prov.Tipo,
                          Prov.Descuento,
                          Prov.ZonaImpuesto,
                          Prov.FormaEnvio,
                          Prov.Proyecto,
                          Prov.Condicion,
                          Prov.Almacen,
                          Prov.Estatus,
                          Prov.DefMoneda,
                          Prov.Mensaje,
                          Prov.CompraAutoCargosTipo,
                          Prov.CompraAutoCargos,
                          Prov.Idioma,
                          Prov.ListaPreciosEsp,
                          Prov.Intercompania,
                          Prov.GarantiaCostos,
                          LC.Descripcion,
                          LC.Uso,
                          LC.Acreedor,
                          LC.VigenciaDesde,
                          LC.VigenciaCondicion,
                          LC.VigenciaHasta,
                          LC.TieneTasaEsp,
                          LC.TasaEsp,
                          TipoAmortizacion.Descripcion,
                          TipoTasa.Descripcion,
                          Descuento.Porcentaje,
                          Agente.Agente,
                          Agente.Nombre,
                          Agente.Estatus,
                          Agente.Mensaje,
                          Alm.Almacen,
                          Alm.Nombre,
                          Alm.Estatus,
                          Alm.Sucursal,
                          Alm.CBDir,
                          UEN.UEN,
                          UEN.Nombre,
                          MensajeLista.Descripcion,
                          MensajeLista.Tipo,
                          VIN.Km,
                          ProyectoDEnFirme.Asunto,
                          CentroCostos.CentroCostos,
                          CentroCostos2.CentroCostos2,
                          CentroCostos3.CentroCostos3
                        --   TipoComprobante.Concepto
                        --   TipoRegistro.Concepto,
                        --   SustentoComprobante.Concepto

                        FROM
                          Compra
                          LEFT OUTER JOIN MovTipo ON 'COMS'=MovTipo.Modulo AND Compra.Mov=MovTipo.Mov
                          LEFT OUTER JOIN Prov ON Compra.Proveedor=Prov.Proveedor
                          JOIN Mon ON Compra.Moneda=Mon.Moneda
                          LEFT OUTER JOIN Descuento ON Compra.Descuento=Descuento.Descuento
                          LEFT OUTER JOIN Alm ON Compra.Almacen=Alm.Almacen
                          LEFT OUTER JOIN Agente ON Compra.Agente=Agente.Agente
                          LEFT OUTER JOIN UEN ON Compra.UEN=UEN.UEN
                          LEFT OUTER JOIN MensajeLista ON Compra.Mensaje=MensajeLista.Mensaje
                          LEFT OUTER JOIN LC ON Compra.LineaCredito=LC.LineaCredito
                          LEFT OUTER JOIN TipoAmortizacion ON Compra.TipoAmortizacion=TipoAmortizacion.TipoAmortizacion
                          LEFT OUTER JOIN TipoTasa ON Compra.TipoTasa=TipoTasa.TipoTasa
                          LEFT OUTER JOIN VIN ON Compra.VIN=VIN.VIN
                          LEFT OUTER JOIN Cte ON Compra.Cliente=Cte.Cliente
                          LEFT OUTER JOIN Condicion ON Compra.Condicion=Condicion.Condicion
                          LEFT OUTER JOIN ProyectoDEnFirme ON Compra.Proyecto=ProyectoDEnFirme.Proyecto AND Compra.Actividad=ProyectoDEnFirme.Actividad
                          LEFT OUTER JOIN CentroCostos ON Compra.ContUso=CentroCostos.CentroCostos
                          LEFT OUTER JOIN CentroCostos2 ON Compra.ContUso2=CentroCostos2.CentroCostos2
                          LEFT OUTER JOIN CentroCostos3 ON Compra.ContUso3=CentroCostos3.CentroCostos3
                          LEFT OUTER JOIN TipoComprobante ON Compra.TipoComprobante=TipoComprobante.TipoComprobante
                          LEFT OUTER JOIN SustentoComprobante ON Compra.SustentoComprobante=SustentoComprobante.SustentoComprobante
                          LEFT OUTER JOIN TipoRegistro ON Compra.TipoIdentificacion=TipoRegistro.TipoRegistro
                         WHERE Compra.ID = ".$id." ";

            $qry2="SELECT
                    CompraD.ID,
                    CompraD.Renglon,
                    CompraD.RenglonSub,
                    CompraD.RenglonID,
                    CompraD.RenglonTipo,
                    CompraD.Almacen,
                    CompraD.FechaRequerida,
                    CompraD.FechaOrdenar,
                    CompraD.FechaEntrega,
                    CompraD.Categoria,
                    CompraD.Codigo,
                    CompraD.Articulo,
                    CompraD.SubCuenta,
                    CompraD.Cantidad,
                    CompraD.CostoConImpuesto,
                    CompraD.Costo,
                    CompraD.CostoInv,
                    CompraD.Impuesto1,
                    CompraD.Impuesto2,
                    CompraD.Impuesto3,
                    CompraD.Descuento,
                    CompraD.DescuentoTipo,
                    CompraD.DescuentoLinea,
                    CompraD.DescuentoImporte,
                    CompraD.DescripcionExtra,
                    CompraD.ReferenciaExtra,
                    CompraD.DestinoTipo,
                    CompraD.Destino,
                    CompraD.DestinoID,
                    CompraD.Cliente,
                    CompraD.Aplica,
                    CompraD.AplicaID,
                    CompraD.CantidadPendiente,
                    CompraD.CantidadCancelada,
                    CompraD.CantidadInventario,
                    CompraD.CantidadA,
                    CompraD.ContUso,
                    CompraD.Unidad,
                    CompraD.Factor,
                    CompraD.ServicioArticulo,
                    CompraD.ServicioSerie,
                    CompraD.Sucursal,
                    CompraD.SucursalOrigen,
                    CompraD.Paquete,
                    CompraD.ImportacionProveedor,
                    CompraD.ImportacionReferencia,
                    CompraD.Retencion1,
                    CompraD.Retencion2,
                    CompraD.Retencion3,
                    CompraD.FechaCaducidad,
                    CompraD.ProveedorArt,
                    CompraD.ProveedorArtCosto,
                    CompraD.Posicion,
                    CompraD.Pais,
                    CompraD.TratadoComercial,
                    CompraD.ProgramaSectorial,
                    CompraD.ValorAduana,
                    CompraD.ID1,
                    CompraD.ID2,
                    CompraD.FormaPago,
                    CompraD.ImportacionImpuesto1,
                    CompraD.ImportacionImpuesto2,
                    CompraD.EsEstadistica,
                    CompraD.PresupuestoEsp,
                    CompraD.Tarima,
                    CompraD.ContUso2,
                    CompraD.ContUso3,
                    CompraD.EmpresaRef,
                    CompraD.ABC,
                    CompraD.Estado,
                    CompraD.PaqueteCantidad,
                    CompraD.ClavePresupuestal,
                    CompraD.TipoImpuesto1,
                    CompraD.TipoImpuesto2,
                    CompraD.TipoImpuesto3,
                    CompraD.TipoImpuesto4,
                    CompraD.TipoRetencion1,
                    CompraD.TipoRetencion2,
                    CompraD.TipoRetencion3,
                    CompraD.TipoComprobante,
                    CompraD.SustentoComprobante,
                    CompraD.TipoIdentificacion,
                    CompraD.DerechoDevolucion,
                    CompraD.Establecimiento,
                    CompraD.PuntoEmision,
                    CompraD.SecuencialSRI,
                    CompraD.AutorizacionSRI,
                    CompraD.VigenteA,
                    CompraD.SecuenciaRetencion,
                    CompraD.Comprobante,
                    CompraD.FechaContableMov,
                    CompraD.TipoImpuesto5,
                    CompraD.Impuesto5,
                    CompraD.CambioImpuesto,
                    AlmPos.Tipo,
                    CB.Codigo,
                    CB.TipoCuenta,
                    CB.Cuenta,
                    CB.SubCuenta,
                    Art.Articulo,
                    Art.Rama,
                    Art.Descripcion1,
                    Art.Grupo,
                    Art.Categoria,
                    Art.Familia,
                    Art.Fabricante,
                    Art.ClaveFabricante,
                    Art.Impuesto1,
                    Art.Impuesto2,
                    Art.Impuesto3,
                    Art.Unidad,
                    Art.UnidadCompra,
                    Art.Tipo,
                    Art.TipoOpcion,
                    Art.DescuentoCompra,
                    Art.PrecioLista,
                    Art.Arancel,
                    Art.Mensaje,
                    Art.TipoCompra,
                    Art.Proveedor,
                    Art.Retencion1,
                    Art.Retencion2,
                    Art.Retencion3,
                    Art.OrigenPais,
                    Art.LotesFijos,
                    Art.ContUso,
                    Art.ContUso2,
                    Art.ContUso3,
                    Art.ObjetoGasto,
                    AlmDetalle.Almacen,
                    AlmDetalle.Estatus,
                    AlmDetalle.Tipo,
                    Cte.Cliente,
                    Cte.Nombre,
                    Cte.Estatus,
                    Cte.Mensaje,
                    CentroCostos.CentroCostos,
                    ProvImportacion.Proveedor,
                    ProvImportacion.Nombre,
                    ProvArt.Proveedor,
                    ProvArt.Nombre,
                    Descuento.Porcentaje,
                    CentroCostos2.CentroCostos2,
                    CentroCostos3.CentroCostos3,
                    ClavePresupuestal.Nombre,
                    ClavePresupuestal.ObjetoGasto,
                    TipoComprobante.Concepto,
                    TipoRegistro.Concepto,
                    SustentoComprobante.Concepto
                    FROM CompraD
                    LEFT OUTER JOIN CB ON CompraD.Codigo=CB.Codigo AND 'Articulos'=CB.TipoCuenta
                    LEFT OUTER JOIN Art ON CompraD.Articulo=Art.Articulo
                    LEFT OUTER JOIN Alm AlmDetalle ON CompraD.Almacen=AlmDetalle.Almacen
                    LEFT OUTER JOIN CentroCostos ON CompraD.ContUso=CentroCostos.CentroCostos
                    LEFT OUTER JOIN Cte ON CompraD.Cliente=Cte.Cliente
                    LEFT OUTER JOIN Prov ProvImportacion ON CompraD.ImportacionProveedor=ProvImportacion.Proveedor
                    LEFT OUTER JOIN Prov ProvArt ON CompraD.ProveedorArt=ProvArt.Proveedor
                    LEFT OUTER JOIN Descuento ON CompraD.Descuento=Descuento.Descuento
                    LEFT OUTER JOIN AlmPos ON CompraD.Almacen=AlmPos.Almacen AND CompraD.Posicion=AlmPos.Posicion
                    LEFT OUTER JOIN CentroCostos2 ON CompraD.ContUso2=CentroCostos2.CentroCostos2
                    LEFT OUTER JOIN CentroCostos3 ON CompraD.ContUso3=CentroCostos3.CentroCostos3
                    LEFT OUTER JOIN ClavePresupuestal ON CompraD.ClavePresupuestal=ClavePresupuestal.ClavePresupuestal
                    LEFT OUTER JOIN TipoComprobante ON CompraD.TipoComprobante=TipoComprobante.TipoComprobante
                    LEFT OUTER JOIN SustentoComprobante ON CompraD.SustentoComprobante=SustentoComprobante.SustentoComprobante
                    LEFT OUTER JOIN TipoRegistro ON CompraD.TipoIdentificacion=TipoRegistro.TipoRegistro
                     WHERE CompraD.ID = ".$id." AND ISNULL(CompraD.Cantidad, 0) <> 0 ORDER BY CompraD.Renglon
                     ";
            break;
        case 'DIN':
            $qry1="SELECT
                      Dinero.ID,
                      Dinero.Empresa,
                      Dinero.Mov,
                      Dinero.MovID,
                      Dinero.FechaEmision,
                      Dinero.UltimoCambio,
                      Dinero.Concepto,
                      Dinero.Proyecto,
                      Dinero.Moneda as Moneda1,
                      Dinero.TipoCambio,
                      Dinero.Referencia,
                      Dinero.DocFuente,
                      Dinero.Observaciones,
                      Dinero.Usuario,
                      Dinero.Autorizacion,
                      Dinero.Estatus,
                      Dinero.Situacion,
                      Dinero.SituacionFecha,
                      Dinero.SituacionUsuario,
                      Dinero.SituacionNota,
                      Dinero.Directo,
                      Dinero.BeneficiarioNombre,
                      Dinero.LeyendaCheque,
                      Dinero.Beneficiario,
                      Dinero.CtaDinero as Cuenta,
                      Dinero.CtaDineroDestino,
                      Dinero.ConDesglose,
                      Dinero.Importe,
                      Dinero.Impuestos,
                      Dinero.Comisiones,
                      Dinero.Saldo,
                      Dinero.FormaPago,
                      Dinero.FechaProgramada,
                      Dinero.Poliza,
                      Dinero.PolizaID,
                      Dinero.OrigenTipo,
                      Dinero.Origen,
                      Dinero.OrigenID,
                      Dinero.FechaConclusion,
                      Dinero.FechaCancelacion,
                      Dinero.Corte,
                      Dinero.CorteDestino,
                      Dinero.InstitucionMensaje,
                      Dinero.InstitucionSucursal,
                      Dinero.InstitucionReferencia1,
                      Dinero.InstitucionReferencia2,
                      Dinero.Sucursal,
                      Dinero.SucursalDestino,
                      Dinero.SucursalOrigen,
                      Dinero.Cajero,
                      Dinero.Mensaje,
                      Dinero.UEN,
                      Dinero.Contacto,
                      Dinero.ContactoTipo,
                      Dinero.TipoCambioDestino,
                      Dinero.CargoBancario,
                      Dinero.CargoBancarioIVA,
                      Dinero.Prioridad,
                      Dinero.Nota,
                      Dinero.Comentarios,
                      Dinero.FechaOrigen,
                      Dinero.ValorOrigen,
                      Dinero.Vencimiento,
                      Dinero.Tasa,
                      Dinero.TasaDias,
                      Dinero.TasaRetencion,
                      Dinero.Retencion,
                      Dinero.ContUso,
                      Dinero.Cliente,
                      Dinero.ClienteEnviarA,
                      Dinero.Proveedor,
                      Dinero.InteresTipo,
                      Dinero.Titulo,
                      Dinero.TituloValor,
                      MovTipo.ReservarCP,
                      Mon.Moneda,
                      Mon.TipoCambio,
                      Mon.TipoCambioVenta,
                      Mon.TipoCambioCompra,
                      CtaDinero.CtaDinero,
                      CtaDinero.Descripcion as Descripcion1,
                      CtaDinero.Tipo,
                      CtaDinero.Moneda,
                      CtaDinero.Estatus,
                      CtaDinero.Mensaje,
                      DineroSaldo.Empresa,
                      DineroSaldo.Moneda,
                      DineroSaldo.CtaDinero,
                      DineroSaldo.Saldo,
                      DineroSaldo.PorConciliar,
                      CtaDineroDestino.CtaDinero,
                      CtaDineroDestino.Descripcion,
                      CtaDineroDestino.Moneda,
                      CtaDineroDestino.Estatus,
                      CtaDineroDestino.Mensaje,
                      Agente.Agente,
                      Agente.Nombre,
                      Agente.Estatus,
                      MensajeLista.Mensaje,
                      MensajeLista.Descripcion,
                      MensajeLista.Tipo,
                      UEN.UEN,
                      UEN.Nombre,
                      CentroCostos.CentroCostos,
                      CentroCostos.Descripcion,
                      Cte.Nombre,
                      CteEnviarA.Clave,
                      CteEnviarA.Nombre,
                      Prov.Nombre,
                      Titulo.Nombre,
                      Titulo.Valor

                    FROM
                      Dinero
                      LEFT OUTER JOIN MovTipo ON 'DIN'=MovTipo.Modulo AND Dinero.Mov=MovTipo.Mov
                      JOIN Mon ON Dinero.Moneda=Mon.Moneda
                      LEFT OUTER JOIN CtaDinero ON Dinero.CtaDinero=CtaDinero.CtaDinero
                      LEFT OUTER JOIN DineroSaldo ON Dinero.Empresa=DineroSaldo.Empresa AND Dinero.Moneda=DineroSaldo.Moneda AND Dinero.CtaDinero=DineroSaldo.CtaDinero
                      LEFT OUTER JOIN CtaDinero CtaDineroDestino ON Dinero.CtaDineroDestino=CtaDineroDestino.CtaDinero
                      LEFT OUTER JOIN Agente ON Dinero.Cajero=Agente.Agente
                      LEFT OUTER JOIN MensajeLista ON Dinero.Mensaje=MensajeLista.Mensaje
                      LEFT OUTER JOIN UEN ON Dinero.UEN=UEN.UEN
                      LEFT OUTER JOIN CentroCostos ON Dinero.ContUso=CentroCostos.CentroCostos
                      LEFT OUTER JOIN Cte ON Dinero.Cliente=Cte.Cliente
                      LEFT OUTER JOIN Prov ON Dinero.Proveedor=Prov.Proveedor
                      LEFT OUTER JOIN CteEnviarA ON Dinero.Cliente=CteEnviarA.Cliente AND Dinero.ClienteEnviarA=CteEnviarA.ID
                      LEFT OUTER JOIN Titulo ON Dinero.Titulo=Titulo.Titulo
                     WHERE Dinero.ID =".$id;

                    $qry2="SELECT
                              DineroD.ID,
                              DineroD.Renglon,
                              DineroD.RenglonSub,
                              DineroD.Importe,
                              DineroD.FormaPago,
                              DineroD.Referencia,
                              DineroD.Aplica,
                              DineroD.AplicaID,
                              DineroD.Sucursal,
                              DineroD.SucursalOrigen,
                              DineroD.ContUso,
                              DineroD.Institucion,
                              DineroValidacion.ID,
                              DineroValidacion.Empresa,
                              DineroValidacion.Mov,
                              DineroValidacion.MovID,
                              DineroValidacion.FechaEmision,
                              DineroValidacion.Saldo,
                              CentroCostos.CentroCostos,
                              CentroCostos.Descripcion,
                              InstitucionFin.Nombre

                            FROM
                              DineroD
                              LEFT OUTER JOIN Dinero DineroValidacion ON 'ROCHE'=DineroValidacion.Empresa AND DineroD.Aplica=DineroValidacion.Mov AND DineroD.AplicaID=DineroValidacion.MovID
                              LEFT OUTER JOIN CentroCostos ON DineroD.ContUso=CentroCostos.CentroCostos
                              LEFT OUTER JOIN InstitucionFin ON DineroD.Institucion=InstitucionFin.Institucion
                             WHERE DineroD.ID = ".$id." ORDER BY DineroD.Renglon, DineroD.RenglonSub ";



            break;
        case 'CXP':
            $qry1 = "SELECT
                      Cxp.ID,
                      Cxp.Empresa,
                      Cxp.Mov,
                      Cxp.MovID,
                      Cxp.FechaEmision,
                      Cxp.UltimoCambio,
                      Cxp.Concepto,
                      Cxp.Proyecto,
                      Cxp.Moneda,
                      Cxp.TipoCambio,
                      Cxp.Usuario,
                      Cxp.Autorizacion,
                      Cxp.Referencia,
                      Cxp.DocFuente,
                      Cxp.Observaciones,
                      Cxp.Estatus,
                      Cxp.Situacion,
                      Cxp.SituacionFecha,
                      Cxp.SituacionUsuario,
                      Cxp.SituacionNota,
                      Cxp.CtaDinero,
                      Cxp.Proveedor,
                      Cxp.ProveedorSucursal,
                      Cxp.ProveedorMoneda,
                      Cxp.ProveedorTipoCambio,
                      Cxp.Condicion,
                      Cxp.Vencimiento,
                      Cxp.Importe,
                      Cxp.Impuestos,
                      Cxp.AplicaManual,
                      Cxp.MovAplica,
                      Cxp.MovAplicaID,
                      Cxp.Saldo,
                      Cxp.FormaPago,
                      Cxp.OrigenTipo,
                      Cxp.Origen,
                      Cxp.OrigenID,
                      Cxp.Poliza,
                      Cxp.PolizaID,
                      Cxp.FechaConclusion,
                      Cxp.FechaCancelacion,
                      Cxp.Dinero,
                      Cxp.DineroID,
                      Cxp.DineroCtaDinero,
                      Cxp.Sucursal,
                      Cxp.SucursalDestino,
                      Cxp.SucursalOrigen,
                      Cxp.Mensaje,
                      Cxp.Cajero,
                      Cxp.UEN,
                      Cxp.Retencion,
                      Cxp.Retencion2,
                      Cxp.Retencion3,
                      Cxp.FechaProgramada,
                      Cxp.Nota,
                      Cxp.Comentarios,
                      Cxp.LineaCredito,
                      Cxp.TipoAmortizacion,
                      Cxp.TipoTasa,
                      Cxp.Amortizaciones,
                      Cxp.InteresesOrdinarios,
                      Cxp.InteresesMoratorios,
                      Cxp.InteresesFijos,
                      Cxp.InteresesAnticipados,
                      Cxp.Comisiones,
                      Cxp.ComisionesIVA,
                      Cxp.VIN,
                      Cxp.ContUso,
                      Cxp.TieneTasaEsp,
                      Cxp.TasaEsp,
                      Cxp.ContratoID,
                      Cxp.ContratoMov,
                      Cxp.ContratoMovID,
                      MovTipo.Modulo,
                    --   MovTipo.Mov,
                      MovTipo.Factor,
                      MovTipo.ReservarCP,
                    --   Mon.Moneda,
                      Mon.TipoCambio,
                      Mon.TipoCambioVenta,
                      Mon.TipoCambioCompra,
                      Prov.Proveedor,
                      Prov.Nombre,
                      Prov.NombreCorto,
                      Prov.Tipo,
                      Prov.Direccion,
                      Prov.EntreCalles,
                      Prov.Plano,
                    --   Prov.Observaciones,
                      Prov.Colonia,
                      Prov.CodigoPostal,
                      Prov.Poblacion,
                      Prov.Estado,
                      Prov.Zona,
                      Prov.Pais,
                      Prov.Telefonos,
                      Prov.Fax,
                      Prov.PedirTono,
                      Prov.Contacto1,
                      Prov.Contacto2,
                      Prov.eMail1,
                      Prov.eMail2,
                      Prov.RFC,
                      Prov.Categoria,
                      Prov.Familia,
                      Prov.Descuento,
                      Prov.ZonaImpuesto,
                      Prov.FormaEnvio,
                      Prov.Comprador,
                    --   Prov.Proyecto,
                      Prov.Condicion,
                      Prov.CtaDinero,
                      Prov.Almacen,
                      Prov.Clase,
                      Prov.Estatus,
                      Prov.UltimoCambio,
                      Prov.Alta,
                      Prov.Conciliar,
                      Prov.Extencion1,
                      Prov.Extencion2,
                      Prov.DiaRevision1,
                      Prov.DiaRevision2,
                      Prov.HorarioRevision,
                      Prov.DiaPago1,
                      Prov.DiaPago2,
                      Prov.HorarioPago,
                      Prov.Beneficiario,
                      Prov.BeneficiarioNombre,
                      Prov.DirInternet,
                      Prov.DefMoneda,
                      Prov.Agente,
                      Prov.Mensaje,
                      Prov.ProntoPago,
                      Prov.DescuentoRecargos,
                      Prov.Pagares,
                      Prov.FormaPago,
                      CxpSaldo.Empresa,
                    --   CxpSaldo.Moneda,
                      CxpSaldo.Saldo as SaldoPendiente,
                      LC.Descripcion,
                      LC.VigenciaDesde,
                      LC.VigenciaCondicion,
                      LC.VigenciaHasta,
                      LC.TieneTasaEsp,
                      LC.TasaEsp,
                      TipoAmortizacion.Descripcion,
                      TipoTasa.Descripcion,
                      MonSaldo.Moneda,
                      MonSaldo.TipoCambio,
                      MonSaldo.TipoCambioVenta,
                      MonSaldo.TipoCambioCompra,
                      CtaDinero.CtaDinero,
                      CtaDinero.Tipo,
                      CtaDinero.Estatus,
                      CtaDinero.Mensaje,
                      CxpPendiente.ID,
                      CxpPendiente.Estatus,
                      CxpPendiente.Empresa,
                    --   CxpPendiente.Mov,
                    --   CxpPendiente.MovID,
                    --   CxpPendiente.Proveedor,
                    --   CxpPendiente.Moneda,
                    --   CxpPendiente.FechaEmision,
                      CxpPendiente.Vencimiento,
                    --   CxpPendiente.Saldo,
                    --   CxpPendiente.Referencia,
                      MensajeLista.Mensaje,
                      MensajeLista.Descripcion,
                      MensajeLista.Tipo,
                      Cajero.Agente,
                    --   Cajero.Nombre,
                      Cajero.Estatus,
                      UEN.UEN,
                    --   UEN.Nombre,
                      VIN.VIN,
                      CentroCostos.Descripcion

                    FROM
                      Cxp
                      JOIN Mon ON Cxp.Moneda=Mon.Moneda
                      JOIN MovTipo ON 'CXP'=MovTipo.Modulo AND Cxp.Mov=MovTipo.Mov
                      JOIN Mon MonSaldo ON Cxp.ProveedorMoneda=MonSaldo.Moneda
                      JOIN Prov ON Cxp.Proveedor=Prov.Proveedor
                      LEFT OUTER JOIN CxpSaldo ON Cxp.Empresa=CxpSaldo.Empresa AND Cxp.ProveedorMoneda=CxpSaldo.Moneda AND Cxp.Proveedor=CxpSaldo.Proveedor
                      LEFT OUTER JOIN CtaDinero ON Cxp.CtaDinero=CtaDinero.CtaDinero
                      LEFT OUTER JOIN CxpPendiente ON Cxp.Empresa=CxpPendiente.Empresa AND Cxp.Proveedor=CxpPendiente.Proveedor AND Cxp.MovAplica=CxpPendiente.Mov AND Cxp.MovAplicaID=CxpPendiente.MovID
                      LEFT OUTER JOIN MensajeLista ON Cxp.Mensaje=MensajeLista.Mensaje
                      LEFT OUTER JOIN Agente Cajero ON Cxp.Cajero=Cajero.Agente
                      LEFT OUTER JOIN UEN ON Cxp.UEN=UEN.UEN
                      LEFT OUTER JOIN LC ON Cxp.LineaCredito=LC.LineaCredito
                      LEFT OUTER JOIN TipoAmortizacion ON Cxp.TipoAmortizacion=TipoAmortizacion.TipoAmortizacion
                      LEFT OUTER JOIN TipoTasa ON Cxp.TipoTasa=TipoTasa.TipoTasa
                      LEFT OUTER JOIN VIN ON Cxp.VIN=VIN.VIN
                      LEFT OUTER JOIN CentroCostos ON Cxp.ContUso=CentroCostos.CentroCostos
                     WHERE Cxp.ID = ".$id;

            $qry2="SELECT
                      MovImpuestoMov.Modulo,
                      MovImpuestoMov.ModuloID,
                      MovImpuestoMov.ID,
                      MovImpuestoMov.Impuesto1,
                      MovImpuestoMov.Impuesto2,
                      MovImpuestoMov.Impuesto3,
                      MovImpuestoMov.Importe1,
                      MovImpuestoMov.Importe2,
                      MovImpuestoMov.Importe3,
                      MovImpuestoMov.SubTotal,
                      MovImpuestoMov.LoteFijo,
                      MovImpuestoMov.Retencion1,
                      MovImpuestoMov.Retencion2,
                      MovImpuestoMov.Retencion3,
                      MovImpuestoMov.OrigenModulo,
                      MovImpuestoMov.OrigenModuloID,
                      MovImpuestoMov.OrigenConcepto,
                      MovImpuestoMov.OrigenFecha,
                      MovImpuestoMov.Excento1,
                      MovImpuestoMov.Excento2,
                      MovImpuestoMov.Excento3,
                      MovImpuestoMov.OrigenDeducible,
                      MovImpuestoMov.SubFolio,
                      MovImpuestoMov.ContUso,
                      MovImpuestoMov.ContUso2,
                      MovImpuestoMov.ContUso3,
                      MovImpuestoMov.DescuentoGlobal,
                      MovImpuestoMov.ImporteBruto,
                      Mov.Mov,
                      Mov.MovID

                    FROM
                      MovImpuesto MovImpuestoMov
                      LEFT OUTER JOIN Mov ON MovImpuestoMov.OrigenModulo=Mov.Modulo AND MovImpuestoMov.OrigenModuloID=Mov.ID
                     WHERE MovImpuestoMov.ModuloID = ".$id."  AND MovImpuestoMov.Modulo = 'CXC'
                    ";
            break;

    }

    $results = run($qry1, 'ASSOC');

    foreach ($results as $key => $value) {
        $data = $value;
    }

    //  printArray($data);

    $details = run($qry2, 'ASSOC');

    // printArray($details);



?>
